name: "📚 Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Runs Every week

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      #- name: "📚  Hashnode Updater"
      #  uses: "varunsridharan/action-hashnode-blog@main"
      - name: Hashnode Blog Action
        uses: Sachin-chaurasiya/hashnode-blog-action@v0.0.8     
        with:
          #USERNAME: 'thirumurthi' # Hashnode Username
          #BLOG_URL: 'https://hashnode.com/@thirumurthi'
          #COUNT: 20 # MAX Visisble
          HASHNODE_PUBLICATION_NAME: 'thirumurthi.hashnode.dev'
          POST_COUNT: 15
          FORMAT: 'list'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_SECRET_BADGE_STORE_CRED }}
