name: "📚 Badges updater"

on:
  schedule:
    # Runs at once a week UTC
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GIT_SECRET_BADGE_STORE_CRED }} # Token in case not using the same repo 
          REPOSITORY: thirumurthis/thirumurthis # optional, By default, it will automatically use the repository who's executing the workflow.
          COMMIT_MESSAGE: "My commit message to update badges" # optional
          CREDLY_USER: thirumurthis # optional, but default will use the same from github
          CREDLY_SORT: RECENT # optional, this is the two forms from credly sort, more popular or recent first, by default use RECENT
